### ISSUE TITLE
Question about inserting = and backspace functionality from a Julia script

### ISSUE THREAD

**Issue by goedman** [jlapeyre/Symata.jl#32]
Hi John,

Right now it is easy to switch to Symata mode and back using "=" and 'backspace'. I'm wondering if it would be possible to do that from a Julia script, e.g. with something like Symata() and Julia() calls replacing "=" and 'backspace'.

An example of how I intend to use it is in 

  https://github.com/goedman/NMfE.jl/blob/master/examples/ch04/ex.5.1_symata.jl

Of course enhancement issue #30 is the next step, but for now above option would be a nice option.

Regards,
Rob

**Comment by jlapeyre** [comment]
Hi Rob,
This is a good idea. I will look into implementing it.
John

**Comment by jlapeyre** [comment]
... Let me know if you have other questions.

Note that you can embed single Symata expressions in Julia code like this
```
@Symata.ex  a = x^2 + y^2 
```

You can also look at the help text for `SetJ`, `JVar`, and `Compile` (eg `? Compile`). These may be useful.

**Comment by goedman** [comment]
Hi John,

That actually works great:

@Symata.ex begin
  xi = {1, 3, 6}
  yi = {1, 5, 10}
  L0(x_) := Simplify( Expand( ((x-xi[2])*(x-xi[3]))/((xi[1]-xi[2])*(xi[1]-xi[3])) ) )
  L1(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[3]))/((xi[2]-xi[1])*(xi[2]-xi[3])) ) )
  L2(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[2]))/((xi[3]-xi[1])*(xi[3]-xi[2])) ) )
  Q(x_) := Simplify(yi[1]*L0(x) + yi[2]*L1(x) + yi[3]*L2(x))
end

I'll study the other options. thanks a lot!

Rob

**Comment by goedman** [comment]
Hi John,

Below is what I ended up with. Very nice!

A few remarks/questions:

1. In my original suggestion I on purpose closely followed the iJulia approach with 'sumata()' and 'Julia()' naively assuming that could easily be adapted to non-iJulia cases. But @Symata.ex works fine.
2. I wasn't able to get '? Compile' to work. '? JVar' and' ? SetJ' do show help. I'm assuming ultimately the intention is for Compile() to return a CompiledFunction with number of arguments and types (as in Mathematica)?
3. What is your intention with the format you return in SetJ (as in the first SetJ below? Am I missing a simple trick to convert this into a function? With the ToString() format a StackOverflow ( http://stackoverflow.com/questions/29778698/julia-lang-metaprogramming-turn-expression-into-function-with-expression-depend ) question suggested below approach. The 2 part answer to that question might enable further programmatic handling (right now I look at Q(x) and decide f(x) has a single argument). But in the end all of this crosses into issue #30 .

Later today I'll close this issue. Thanks again!

Regards,
Rob

@Symata.ex begin
  xi = {1, 3, 6};
  yi = {1, 5, 10};
  L0(x_) := Simplify( Expand( ((x-xi[2])*(x-xi[3]))/((xi[1]-xi[2])*(xi[1]-xi[3])) ) );
  L1(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[3]))/((xi[2]-xi[1])*(xi[2]-xi[3])) ) );
  L2(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[2]))/((xi[3]-xi[1])*(xi[3]-xi[2])) ) );
  Q(x_) := Simplify(yi[1]*L0(x) + yi[2]*L1(x) + yi[3]*L2(x));
  SetJ(q, Q(x))
  SetJ(qs, ToString(Q(x)))
  Print("Q(x) = ", Q(x), "\n")
end;

@Symata.ex Print("Q(4.5) = ", Q(4.5), "\n");
q3=parse(qs)
@eval f(x) = $(q3)
xint = 1:0.1:6   # FloatRange
using Plots;pyplot(size=(700,700))
p = plot(xint, f.(xint), line=(:path, 1), label="interpolated curve")

**Comment by goedman** [comment]
Hmm, above shortened example (in https://github.com/goedman/NMfE.jl/blob/master/test/ch04_symata.jl ) doesn't work while it seems to work fine in the original program. Symata complains about 'isless' in the SetJ calls. Puzzling.

**Comment by jlapeyre** [comment]
Hi Rob,

Thanks for the feedback. It is important because I can't predict use cases.  You can close the issue whenever you are satisfied, there is no hurry.

Some of what I wrote above (including `Compile` apparently) may apply only to development versions. You can try `Pkg.checkout("Symata")` to switch to the development branch. (after updating, or issuing `git pull` in the Symata directory). You can find some information about `Compile` in  1) its doc string, 2) the notebook examples in `./examples`,  3) the test code in `./sjtest`. (I don't recall which file at the moment)

* There is now an exported macro `@sym` that is exactly the same as `@Symata.ex`. This macro is better semantically and has three characters. (btw. `@ex` was already exported, but I removed this.)

* There may still be a better way thatn `@sym begin ... end`, but I agree that this looks good for now. For going the other way--- embedding Julia in Symata, there is `:( julia code)`, but I am not sure how robust this in in a file.

* `Compile` is only partially implemented. It should be easy to add most things (you can look at the code yourself). If there is something missing that you need, let me know. It differs a bit from Mma in a few ways. 
 * You can give a list of arguments, ie. `x` or `[x,y]`, etc. But, if you don't, `Compile` searches the code for unbound (in Julia) variables and assumes they are arguments.
 * You don't have to (and at present cannot) annotate the type, as is necessary in Mma. This is, of course, because the host language is `Julia`, so we let it do type inference, etc. during compiling.

* Construction of literal lists in Symata is done like this `[1,2,3]`. I forgot that `{1,2,3}` still works (or ever did!). I should probably remove the second method. There are good reasons to use the Mma syntax (eg, Symata is similar to Mma), and not to use it (eg, everyone else uses () for functions).  Since I currently use the Julia lexer and parser, I don't have a choice, Symata statements have to be parsed as legal Julia statements (although they may cause errors if evaluated as Julia code)

* As in Julia, juxtaposition for multiplication only works with a number as the first factor, ie `3x`. Your expressions like `(x-y)(a-b)` are interpreted with `(x-y)` as the head of an expression. You can see this using `Head` and `Args`. However, the full expression is not printed correctly, so this is obscured (I only recently changed Symata to allow these heads (or rather protect them from Currying) so the display is sometimes incorrect.)  This ambiguity is possible because Symata uses the parens for both function call and grouping. This may need to be changed if such heads are actually necessary or useful.  I don't want Symata to be exactly like Mma, but I am discovering that Mma is pretty tightly engineered, so that there is not much freedom in choosing behavior.

    Please let me know if this does not fix the error.

* I'll have to look at your plotting example later, when I have more time. I did a quick implementation of `Plot`. It is probably not too hard to extend it to your use case, if it does not already work. OTOH, there is no reason not to plot from Julia, ir that is convenient.

* Apropos the previous item, there are `Pack` and `Unpack` for moving arrays between Julia and Symata. As with other functions, these are only partly implemented; they work for 1 dimensional arrays.

John

**Comment by jlapeyre** [comment]
btw. Functions are as follows, and only some of these are supported by `Plot`. (As much as possible, I simply pass arguments to `Plots::plot`)  This could be extended without too much effort, but it would take an hour or two, or so. One way to plot a function, although not super convenient, is to generate a list of pairs within Symata and then plot these.

1. `f(x_) := x^2`,

2. f = :( x -> x^2 ), which binds Symata `f` to a Julia function.

3. `f = x -> x^2`, or `f = Function(x, x^2)`.  A Symata Pure function.

4. `f = Compile(x^2)`. In this example, the result is identical to 1.

**Comment by jlapeyre** [comment]
I tried the following, simply adding `*` for multiplication where necessary. I think it plots what you want.


```julia
using Symata

@sym begin
xi = {1, 3, 6};
yi = {1, 5, 10};
L0(x_) := Simplify( Expand( ((x-xi[2])*(x-xi[3]))/((xi[1]-xi[2])*(xi[1]-xi[3])) ) );
L1(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[3]))/((xi[2]-xi[1])*(xi[2]-xi[3])) ) );
L2(x_) := Simplify( Expand( ((x-xi[1])*(x-xi[2]))/((xi[3]-xi[1])*(xi[3]-xi[2])) ) );
Q(x_) := Simplify(yi[1]*L0(x) + yi[2]*L1(x) + yi[3]*L2(x));
SetJ(q, Q(x))
SetJ(qs, ToString(Q(x)))
Print("Q(x) = ", Q(x), "\n")
end;

@Symata.ex Print("Q(4.5) = ", Q(4.5), "\n");
q3=parse(qs)
@eval f(x) = $(q3)
xint = 1:0.1:6 # FloatRange
using Plots;pyplot(size=(700,700))
p = plot(xint, f.(xint), line=(:path, 1), label="interpolated curve")
```

However, `Compile` only works with literal expressions. I think this is what `Mma` does as well, with an option to evaluate the RHS. I guess Mma does not evaluate by default, because users do not want their function expressions rewritten by the evaluation sequence, because the resulting expression may be inefficient.

**Comment by goedman** [comment]
Thank you John. Can't believe I didn't spot the '*' omission in the shortened version! Switched to master and @sym and [] for arrays. '?Compile' works fine in master as well. 

In my case I prefer to use Plots from Julia because it'll be mixed with finite element result plots. Next step to go carefully through all of the Symata tests.

Your help has been extremely useful John, thanks again. I'll close this issue.
