### ISSUE TITLE
Just a question, not really an issue.

### ISSUE THREAD

**Issue by goedman** [jlapeyre/Symata.jl#69]
Hi John,

I was just wondering if there is something specific (or just time constraints or limited sympy support) why DSolve is currently flagged as not working.

It seems there is kind of a pattern in how you implement calls to the underlying layer of sympy, but I haven't really figured that out. 

Regards,
Rob

**Comment by jlapeyre** [comment]
Hi Rob,

Sorry about the long silence. Yes, time constraints!

I would take the time to document how to develop Symata if I thought someone would use it. If you are interested, I am happy to assist. There are indeed some patterns for adding functionality. One way is to write in [Symata](https://github.com/jlapeyre/Symata.jl/blob/master/symsrc/autoloaded.sj). But that won't help for DSolve.

The first thing is to use the newer macros for writing the interface instead of the older method which the (broken) `DSolve` currently uses. See `Solve` as an example.

```julia
@mkapprule DSolve
@doap function DSolve(expr,vars)
  ...
end
```

[Here is one of the methods for `Solve`](https://github.com/jlapeyre/Symata.jl/blob/master/src/sympy_application.jl#L487-L493)

Line 488 and 489 convert the input parameters from Julia to Python (sympy objects).

In line 490, `res = sympy[:solve](pyexpr,pyvar)` calls a sympy function named `solve`. The function `sympy[:dsolve]` also exists. The return value `res` will also be a sympy object. Line 491 converts `res` to a Julia object.

The last line 492 creates the Symata expression that is returned. In this case, a nested expression of `Lists` and `Rules`. Each expression and subexpression has a head and arguments, just like in Mma.
`mxpr(:List,1,2,3)` creates a Symata list `[1,2,3]`.  If you load Symata via `using Symata` at the command line, then help for many developer functions, such as `mxpr` and `mxpra` is available. I am not sure why `DSolve` is not working, but I guess that it can be implemented in a way very similar to `Solve`.  One thing to do is to search for the sympy documentation for `dsolve`. You find an example call `dsolve(Derivative(f(x), x, x) + 9*f(x), f(x))`.  You can enter the sympy shell from Julia with `isympy()` and check that the example works. I try the following which essentially does what you want  the Symata function `DSolve` to do, but breaks it into steps.

```julia
julia> df = @sym ToSymPy(Derivative(f(x),x,x) + 9*f(x))
Out(3) = PyObject Derivative(f(x), x, x) + 9*f(x)
julia> dv = @sym ToSymPy(f(x))
Out(4) = PyObject f(x)
julia> sympy[:dsolve](df,dv)
```
The last line give an error because `df` is `not a differential equation`.  My best guess is that julia `:Derivative` is translated to some sympy object called `Derivative`, but not the correct one.  sympy is built around OO object class hierarchies. Digging around in these can be frustrating.

**Comment by jlapeyre** [comment]
Here is more trouble shooting. This works
```julia
julia> df2 = PyCall.pyeval("Derivative(f(x), x, x) + 9*f(x)")
PyObject 9*f(x) + Derivative(f(x), x, x)

julia> sympy[:dsolve](df2,dv)
PyObject Eq(f(x), C1*sin(3*x) + C2*cos(3*x))
```
Using this does not
```julia
julia> df3 = @sym ToSymPy(Derivative(f(x), x, x) + 9*f(x))
Out(18) = PyObject Derivative(f(x), x, x) + 9*f(x)
```

Here is a clue as to why
```julia
julia> pytypeof(df2[:args][2])
PyObject <class 'sympy.core.function.Derivative'>

julia> pytypeof(df3[:args][2])
PyObject Derivative
```

But we can do this
```
julia> sympy[:Derivative]
PyObject <class 'sympy.core.function.Derivative'>
```

This means we have to define a translation for julia `:Derivative` to the python clas returned by `sympy[:Derivative]`. This is done is sympy.jl

**Comment by jlapeyre** [comment]
... finding out how to do this can be maddening.
```julia
julia> sympy[:Derivative]
PyObject <class 'sympy.core.function.Derivative'>

julia> sympy[:Add]
PyObject <class 'sympy.core.add.Add'>

julia> sympy[:Log]
ERROR: KeyError: key "Log" not found

julia> sympy[:log]
PyObject log
```

But, upon inspection I see that I have already translated `sympy[:Derivative]`  [here](https://github.com/jlapeyre/Symata.jl/blob/master/src/sympy.jl#L229).  So I write

```julia
@mkapprule DSolve

@doap function DSolve(expr, fcn)
    pyexpr = expr |> sjtopy
    pyfcn = fcn |> sjtopy
    res =  sympy[:dsolve](pyexpr,pyfcn)
    sres = res |>  pytosj
end
```

And now the following works!

```julia
symata 1> DSolve(D(f(x),x,x) + 9*f(x), f(x))
Out(1) = f(x) == (C2*Cos(3x) + C1*Sin(3x))
```

I pushed this change to github.

**Comment by goedman** [comment]
Hi John, thanks for the responses. I'm traveling right now, but a quick check indeed showed DSolve in Symata works! I will study the full thread in more detail after my return to the US on Thursday!

Good to see you're back, but I realize we're all busy. Absolutely no need to apologize for a long silence!

Regards,
Rob
